### ISSUE TITLE
$save removes associated models on return

### ISSUE THREAD

**Issue by MikaAK** [strongloop/loopback-sdk-angular#120]
Recently I noticed that using `model.$save()` will cause any relational data to be lost on success. 
### example

``` javascript
console.log(myModel)
myModel.$save(function(data) {
  console.log(myModel)
})
```
#### Before Call

``` json
{
"ownerId": "4",
"owner": { "ownerData": "true" },
"name": "bob",
"agentId": "5",
"agent": {"agentData": "false"}
}
```
#### After Call

``` json
{
"ownerId": "4",
"name": "bob",
"agentId": "5",
}
```

**Comment by bajtos** [comment]
Here is what is happening under the hood:

- `myModel.$save` sends the data ("before call") in the request to the LoopBack server. 

- Since LoopBack does not support updating related models in a single request (see https://github.com/strongloop/loopback/issues/644 and https://github.com/strongloop/loopback/issues/583), it silently discards the related data and returns only the model properties in the response ("after call"). 

- Angular updates the local model using the data returned by the server, dropping the related models along the way.

Possible workaround: instead of calling `myModel.$save`, call the `upsert` method and then manually update the model with the data returned from the server.

```js
console.log(myModel)
MyModel.upsert({}, myModel, function(data) {
  // a simplistic copy which does not remove
  // properties deleted on the server
  for (var key in data) {
    myModel[key] = data[key];
  }
});
```

**Comment by mariohmol** [comment]
just to confirm, if i upsert a model with childs, it wont update the attributes changed in child/related modesl.. correct?

in this example, owner and agent will not be updated..

**Comment by k3n3l** [comment]
Hi

I have the same problem, when I try to save a modified object, without make changes on relative attributes, these are lost.

**Comment by jonathanwoahn** [comment]
I'm having this same issue. What would be awesome is if we could include the filter object into the save request - something like this:

`Model.$save({filter:{include:{relation:'otherModel'}}})`

Then we could specify what we want to on the return response.

**Comment by bajtos** [comment]
Hello, I am afraid we don't have bandwidth to fix this issue.
