### ISSUE TITLE
resourceInstance.$save not working correctly with ACLs on model-instance level

### ISSUE THREAD

**Issue by cebor** [strongloop/loopback-sdk-angular#154]
I just noticed that `resourceInstance.$save` does not work how it should.

Example: 

```javascript
// GET user
var user = User.findById({id: userId});

// wait until promise is resolved

// change user property
user.username = "newUserName";

// PUT changes to Server
user.$save
```

The problem is that the `$save` method does the PUT request on a wrong URL:

```http
# WRONG URL
PUT http://localhost:3000/api/User?id=557bf9a26fa06aed190c5d0c

# CORRECT URL should be
PUT http://localhost:3000/api/User/557bf9a26fa06aed190c5d0c
```

On Models where i don't need an auth it works, but on models where i need to be authed like the User it does not.

I don't know if this is a AngularJS problem or something with the loopback generated `lb-services.js`.

Im using the latest version of strongloop/loopback and AngularJS 1.4.

**Comment by bajtos** [comment]
The current behaviour is the result of an intentional decision made while developing loopback-sdk-angular. Consider the following example:

```js
var user = new User({ id: '557bf9a26fa06aed190c5d0c', email: 'user@example.com' });
user.$save();
```

The client cannot tell whether `user.$save` is updating an existing record, or whether a new record with a pre-set id should be created instead. The safest (and the simplest) solution is to call `updateOrCreate` (`PUT http://localhost:3000/api/User)` and let the server take care.

I understand this situation is rather unfortunate. From the top of my head, I can see following paths to solve the problem:
 - Fix the ACL system to support `updateOrCreate`.
 - Modify the Angular client and try to detect whether $save is calling UPDATE or CREATE.

As a temporary workaround, you can call `updateAttributes` yourself whenever you know that an existing record is being updated.

```
// GET user
var user = User.findById({id: userId});

// wait until promise is resolved

// change user property
user.username = "newUserName";

// PUT http://localhost:3000/api/User/557bf9a26fa06aed190c5d0c
User.prototype$updateAttributes({ id: user.id }, user);
```

**Comment by raymondfeng** [comment]
The behavior of `PersistedModel.prototype.save()` is as follows:

1. If the `id` is present, try update
2. If the `id` is missing, try insert

I think Angular should allow it.

**Comment by bajtos** [comment]
Related discussion: https://github.com/strongloop/loopback-sdk-angular/issues/89

**Comment by bevinhex** [comment]
I solved it by adding
```
"updateById":{
            url: urlBase + "/miscTodos/:id",
            method: "PUT"
        },
```
under findById in lb-services.js file, for now working great

**Comment by bajtos** [comment]
@bevinhex I believe you can use the builtin method `prototype$updateAttributes` instead of adding a custom one.

```js
MiscTodo.prototype$updateAttributes({ id: note.id }, note);
```

**Comment by ahmed-abdulmoniem** [comment]
@bajtos Does prototype$updateAttributes fire loopback validations?

**Comment by bajtos** [comment]
>  Does prototype$updateAttributes fire loopback validations?

Not by default, see http://loopback.io/doc/en/lb2/Model-definition-JSON-file.html#advanced-options

**Comment by ahmed-abdulmoniem** [comment]
Thanks

**Comment by dylandechant** [comment]
this is now prototype$patchAttributes?

docs are not showing this.

**Comment by bajtos** [comment]
> this is now `prototype$patchAttributes`?

Yes.
