### ISSUE TITLE
Support Collections and LiveSets

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-sdk-angular#156]
This depends on:
 - Collections and LiveSets https://github.com/strongloop/loopback/issues/1418
 - Angular SDK Change Stream support https://github.com/strongloop/loopback-sdk-angular/issues/155

Below is a more detailed proposal. I think we should build this outside the **loopback-sdk-angular** repo / module.

```js
// basic usage
function myCtrl(MyModel, LiveSet) {
  var options = ...; // could include things like filter
  var set = new LiveSet(MyModel, options);
  $scope.items = set.toLiveArray();
}
```

Here is some very basic high level code that illustrates the important details.

 - using `EventSource` to consume the `ChangeStream`
 - need to be able to hook into `AngularPersistedModel`
 - need to get and add `AccessToken` to the `EventSource` url

```js
// in a separate loopback-angular-live-set module / repo
function LiveSet(PersistedModel, options) {
  var set = this;
  var url = getApiUrl(PersistedModel);
  var modelUrl = getModelUrl(PersistedModel);
  var options = stringifyAsQs(getOptions(options));
  var fullUrl = url + '/' + modelUrl + '/createChangeStream?' + options;
  var accessToken = getToken();
  if (accessToken) {
    fullUrl += '&access_token=' + accessToken;
  }
  fullUrl += '&_format=event-source';

  var es = this.eventSource = new EventSource(fullUrl);

  // when someone calls a PersistedModel method
  // that modifies something (insert, update, delete)
  this._hookPersistedModel(PersistedModel);

  // apply event stream changes
  es.on('data', function(e) {
    var change = JSON.parse(d.data);

    // applyChange needs to take into account
    // when a outgoing change conflicts with an incoming change
    // it should ignore the incoming change and after the
    // outgoing change completes, refresh the model in question
    set.applyChange(change);
  });
}

// called when a PersistedModel method is called
// before it completes
LiveSet.prototype._beforeModify = function() {
  // save the current version
  // apply the modification locally
}

LiveSet.prototype._modificationSuccess = function() {
  // unref the saved previous version
}

LiveSet.prototype._modificationError = function() {
  // replace the modified version with the 
  // saved previous version
}
```

**Comment by ritch** [comment]
@bajtos can you take a look at this ^^^

**Comment by bajtos** [comment]
This looks great! I especially like that we will reuse an existing standard (EventSource) instead of trying to invent our own solution.

> I think we should build this outside the loopback-sdk-angular repo / module

+1, small independent modules FTW.

Having said that, creating a new project adds extra overhead. As an alternative, we could keep this new feature in a standalone source file living in this repository. Conceptually, keep the implementation as in two modules, but package them in a single npmjs package.

I think versioning is the most important factor affecting the decision. If we want to version LiveSet implementation independently from the Angular SDK, then it should live in its own module.

I am ok with both ways.

> need to get and add AccessToken to the EventSource url

You should be able to get the access token via `LoopBackAuth` service and its property `accessTokenId`, see [services.template.ejs](https://github.com/strongloop/loopback-sdk-angular/blob/e7dde54e81fe19e8d9c60a4515f03e23321021e8/lib/services.template.ejs#L329-L330).

> need to be able to hook into AngularPersistedModel

This may be tricky to implement in the right way, without introducing coupling between a LiveSet and a Model resource.

Here is one possible solution: modify the current code-generator to add a `response interceptor` to selected CRUD methods (create, $save, etc.), this interceptor should emit a generic event e.g. `changed`. The LiveSet can install a listener for this event. See "actions" param in [docs](https://docs.angularjs.org/api/ngResource/service/$resource#usage) for more details about the interceptor.

> ```
fullUrl += '&_format=event-source'
```

I like this idea. 

Perhaps we can modify the current streaming implementation in strong-remoting to support different response formats? At the moment, we use demux stream (like `&_format=demux-json-newline`). If response format selection turns out to be difficult to implement, then I think it's ok to hard-code the response format in the stream arg description (e.g. replace `json: true` with `event-stream: true`) and force all consumers of `createChangeStream` to use EventSource protocol instead of demux. Anyways, that's just me thinking aloud :)

**Comment by ritch** [comment]
> Perhaps we can modify the current streaming implementation in strong-remoting to support different response formats?

I've added support for `_formate=event-source`. I should add `demux-json-newline`... Its actually techincally supported right now (its just not evenr referenced in the code and is just the default).
