### ISSUE TITLE
Use strong-remoting instead of ngResource

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-sdk-angular#157]
In order to support advanced features provided by the server, we should use strong-remoting in the angular client. This has quite a few benefits:

 - adapters (write app code against the angular sdk api, and swap from http to other adapters)
 - less generated code (use a serialization of `app.remotes()` instead of templated code)
 - stream support

There are also a few drawbacks:

 - doesn't use `ngHttp` client
 - includes code that might not be useful (eg. node streams)

**Comment by ritch** [comment]
What if we create a custom angular adapter that uses `ngHttp` (and supports `PersistedModel.subscribe()` but without streams?).

**Comment by bajtos** [comment]
> adapters (write app code against the angular sdk api, and swap from http to other adapters)

+1

> less generated code (use a serialization of app.remotes() instead of templated code)

My original implementation of the Angular SDK was based on a similar approach, where we took remoting metadata and then dynamically built the Angular resources at runtime. The feedback from @seanbrookes was that such SDK is difficult to understand for consumers, as it's not clear what methods are available, what are their arguments, etc. Therefore I have rewritten the generator to produce a static code that does not build any dynamic resources at runtime, and that also includes extensive ngdoc comments.  I think this is an important aspect that should be preserved in the new strong-remoting based version too.

Perhaps we can store the per-method remoting metadata inside the code-generated methods, instead of storing all remoting metadata in a single global lookup table?

An example to illustrate my idea:

```js
/**
 * @ngdoc
 * @method
 * @name User.create
 * @methodOf User
 *
 * Create a new instance of the model and persist it into the data source.
 *
 * (describe params and return value)
 */
User.create = function(data) {
  return this._sharedClass.invokeMethod(
    {
      name: 'create',
      accepts: { arg: 'data', type: 'object', http: { source: 'body' } },
      returns: { type: 'User', root: true },
      http: { verb: 'post', path: '/' }
    },
    {
      data: data
    });
};
```

> includes code that might not be useful (eg. node streams)

The bundle size is very important. IIRC, the `request` module we use in strong-remoting client depends on crypto, which adds about 1MB of source codes to the bundle. Of course, this can be mitigated by using ngHttp instead.

For comparison, the code we generate now for LoopBack built-in models is about 20KB, uglified 14KB and gzipped about 2.3KB.

When it comes to streams, I think the ReadableStream has about 40kb, which may be acceptable.

> doesn't use ngHttp client

IMO this is a show-stopper. If we don't use ngHttp under the hood, then I think we will soon have to re-implement many of its features. I am also not sure if there is a way how to support standard Angular HTTP interceptors from such custom HTTP client, in which case SDK users won't be able to reuse the same interceptors for both SDK and non-SDK calls. See for example https://github.com/strongloop/loopback-sdk-angular/issues/146.

> What if we create a custom angular adapter that uses ngHttp (and supports PersistedModel.subscribe() but without streams)?

+1 and +1

I think it's a good idea to implement PeristedModel.subscribe() without streams. It seems to me that we need only a very small subset of streams API/features, thus I hope it should be relatively easy to build our own lightweight abstraction.

BTW regarding PersistedModel.subscribe(): I am wondering how far we can get with using XMLHttpRequest for streaming calls. AFAIK, there is no way how to discard processed chunks, the browser always keeps the full response body. This may create a memory-leak-like situation when the page is open for long time, as we will keep all change stream events emitted since the connection was opened. See [A proposal for streaming XHR](http://maxogden.com/a-proposal-for-streaming-xhr.html) for more details and also an implementation of a streaming consumer built on top of XHR.

**Comment by ritch** [comment]
This doesn't really seem to be going anywhere in the short term and I don't really need it for the advanced features mentioned in the description. What i've done is implemented support for `EventSource` in both my client (angular-live-set) and on the server.

I'm going to close this. @bajtos re-open if you disagree.
