### ISSUE TITLE
Quota exceeded on local/session-storage in Safari Ingocnito-mode

### ISSUE THREAD

**Issue by AlmaasAre** [strongloop/loopback-sdk-angular#179]
It would be nice to wrap all the calls to sessionStorage and localStorage in a try/catch, and use a memory storage as a fallback when they are not supported.

Seems like both local and sessionStorage explodes with errors about Quota exceeded on Safari in incognito mode. And i suspect the same thing goes for safari on ios 7..

http://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an

**Comment by kennethlynne** [comment]
https://gist.github.com/juliocesar/926500 

try catch å skrive og lese til localstorage og session storage, og failer det så fall back til det (in memory storage).

**Comment by kennethlynne** [comment]
https://gist.github.com/remy/350433

**Comment by bajtos** [comment]
@davidcheung IMO this is major bug, our SDK should support incognito mode out of the box.

As for the solution - I'd prefer to check whether `window.localStorage` is defined, and if it's not, then save/load operation should become no-ops.

@AlmaasAre @kennethlynne this bug is pretty easy to fix, would you mind contributing the patch yourself? Here is the place where to start looking: [lib/services.template.ejs#L303-L314](https://github.com/strongloop/loopback-sdk-angular/blob/d170fd94e4a4fd3a36ec03e653c35ded5270a9f1/lib/services.template.ejs#L303-L314)

**Comment by AlmaasAre** [comment]
Lot to do in the coming days, but if i have time, then sure. It's a low hanging fruit

window.localStorage is defined in ingocnito mode in safari, that's the problem. So have try to save something to localStorage and wrap it with a try/catch, and fallback to memory if exception is thrown.

**Comment by bajtos** [comment]
@AlmaasAre I don't have a strong opinion, I'm ok with any approach that keeps the code reasonably simple and easy to maintain.
