### ISSUE TITLE
[Feature]$save() on instance must follow url as instance generation

### ISSUE THREAD

**Issue by totalard** [strongloop/loopback-sdk-angular#266]
Dear,

What Currently Now
`Post.comments.findById({id:1,fk:2})`
generates Url as `GET posts/1/comments/2`

after i uses `$save()` on this instance.
the url generated is `PUT/PATCH comments/2`
the `posts/1` is missing.

It should be 
`PUT/PATCH posts/1/comments/2`

Hope you got it.

**Comment by bajtos** [comment]
Hello @totalard, thank you for reporting the issue, your description makes sense to me. To be honest, I think both URLs (`/comments/2` and `/posts/1/comments/2`) are valid in a way. `Post.comments.findById` returns a `Comment` instance which is not aware of how it was retrieved from the server, that's why it calls `/comments/2` on save.

Having wrote that, I see how this can be an issue and I think it's a reasonable idea to change `$save` to honour the relation-based URL.

Would you like to contribute this improvement yourself? I am happy to help you along the way. See http://loopback.io/doc/en/contrib/index.html to get started.

**Comment by bajtos** [comment]
Closing as we don't have bandwidth to implement this ourselves.
